clear all;
close all;
clc;
disp('Please enter the value of resistance R:');
R=input('');
disp('Please enter the value of inductance L:');
L=input('');
disp('Please enter the value of capacitance C:');
C=input('');
fr=1/(2*pi*sqrt(L*C));
disp('The resonant frequency(in hertz) for the given circuit is:');
disp(fr);
disp('The resonant frequency(in rad/s) for the given circuit is:');
disp(2*pi*fr);
BW=1/(2*pi*R*C);
disp('The band width BW of the parallel RLC circuit is:');
disp(BW);
Q=fr/BW;
disp('The Q factor of the parallel RLC circuit is:');
disp(Q);
f1=fr-(BW/2);
f2=fr+(BW/2);
disp('The lower and upper cut-off frequencies for the given parallel RLC circuit are:');
disp(f1);
disp(f2);
% To calculate impedance of the circuit
disp('Please enter the maximum value of AC current source:');
I=input('');
Irms=I/sqrt(2);
disp('Please enter the frequency in rad/s:');
w=input('');
Z=1/sqrt((1/R)^2+(C*w-1/(L*w))^2);
Vrms=Irms*Z;
disp('The voltage(rms) appearing across the parallel elements are:');
disp(Vrms);
syms f;
subplot(3,2,1);
fplot(@(f) 1/sqrt((1/R)^2+(2*pi*f*C-1/(2*pi*f*L))^2),[fr-50 fr+100]);
xlabel('Frequency(Hz)-------->');
ylabel('Impedance(ohm)--------->');
title('Z v\s f');
subplot(3,2,2);
% Vm=Im*Z
fplot(@(f) 10/sqrt((1/R)^2+(2*pi*f*C-1/(2*pi*f*L))^2),[fr-50 fr+100]);
xlabel('Frequency(Hz)-------->');
ylabel('Max voltage(V)--------->');
title('Vm v\s f');
subplot(3,2,3);
% Vrms=Irms*Z
fplot(@(f) (10/sqrt(2))/sqrt((1/R)^2+(2*pi*f*C-1/(2*pi*f*L))^2),[fr-50 fr+100]);
xlabel('Frequency(Hz)-------->');
ylabel('Rms voltage(V)--------->');
title('Vrms v\s f');
subplot(3,2,4);
fplot(@(f) (10/sqrt((1/R)^2+(2*pi*f*C-1/(2*pi*f*L))^2))/R,[fr-50 fr+100]);
xlabel('Frequency(Hz)-------->');
ylabel('Max current in resistor(A)--------->');
title('Ir v\s f');
subplot(3,2,5);
fplot(@(f) (10/sqrt((1/R)^2+(2*pi*f*C-1/(2*pi*f*L))^2))/(L*2*pi*f),[fr-50 fr+100]);
xlabel('Frequency(Hz)-------->');
ylabel('Max current in inductor(A)-------->');
title('Il v\s f');
subplot(3,2,6);
fplot(@(f) (10/sqrt((1/R)^2+(2*pi*f*C-1/(2*pi*f*L))^2))*(C*2*pi*f),[fr-50 fr+100]);
xlabel('Frequency(Hz)-------->');
ylabel('Max current in capacitor(A)-------->');
title('Ic v\s f');