clear all;
close all;
clc;
disp('Enter the value of current source:');
I=input('');
disp('Please enter the value of R1:');
R1=input('');
disp('Please enter the value of R2:');
R2=input('');
disp('Please enter the value of R3:');
R3=input('');
disp('Please enter the value of XL1:');
XL1=input('');
disp('Please enter the value of XL2:');
XL2=input('');
disp('Please enter the value of XC1:');
XC1=input('');
Zth=(R2+j*(XL1-XC1))*(R3+j*XL2)/(R2+R3+j*(XL1+XL2-XC1));
disp('The Thevenin impedance is calculated as:');
disp(Zth);
Isc=(i*(XC1*I))/(-R2+i*(XC1-XL1));
disp('The short circuit current is calculated as:');
disp(Isc);
Vth=Isc*Zth;
disp('The Thevenin voltage is calculated as:');
disp(Vth);
disp('The Norton equivalent current source is:');
disp(Isc);
disp('The value of Z(load) for maximum power transfer is:'); 
disp(conj(Zth));
