% Un-balanced Y-delta positive system
clear all;
close all;
clc;
disp('Please enter the value of phase voltage(ref----phase angle=0):');
Van=input('');
Vbn=(Van*cos(deg2rad(-120))+i*Van*sin(deg2rad(-120)));
Vcn=(Van*cos(deg2rad(-240))+i*Van*sin(deg2rad(-240)));
disp('Please enter Raa1:');
Raa1=input('');
disp('Please enter Rbb1:');
Rbb1=input('');
disp('Please enter Rcc1:');
Rcc1=input('');
disp('Please enter Zab:');
Zab=input('');
disp('Please enter Zbc:');
Zbc=input('');
disp('Please enter Zca:');
Zca=input('');
Z=[(Raa1+Rbb1+Zab) -Rbb1 -Zab;Zab Zbc -(Zab+Zbc+Zca);-Rbb1 (Rbb1+Rcc1+Zbc) -Zbc];
V=[Van-Vbn;0;Vbn-Vcn];
I=inv(Z)*V;
disp('The respective loop currents are:');
disp(I);
disp('Thus the respective line currents are:');
disp(I(1));
disp(I(2)-I(1));
disp(-I(2));