var ig_a=true,ig_=null,ig_b=false,ig_c;function ig_d(a){var b=window;if(a!="")for(a=a.split(".");a.length;){var c=a.shift();if(typeof b[c]!="object")b[c]={};b=b[c]}return b}(function(){function a(c,d){c=ig_d(c);for(var e=0;e<d.length;e+=2)c[d[e]]=d[e+1]}function b(c,d,e,f,h){if(f)for(var g=0;g<f.length;g+=2)e.prototype[f[g]]=f[g+1];if(h)for(g=0;g<h.length;g+=2)e[h[g]]=h[g+1];a(c,[d,e])}a("",["_exportSymbols",a]);a("",["_exportClass",b])})();function ig_e(a,b,c){if(!a.className)return ig_b;for(var d=a.className.split(" "),e=[],f=ig_b,h=0;h<d.length;++h)if(d[h]!=b)e.push(d[h]);else{f=ig_a;c&&e.push(c)}a.className=e.join(" ");return f};function ig_f(a){a=a||document.location.href;var b=a.indexOf("?");if(b==-1)return"";var c=a.indexOf("#");a=c==-1?a.substr(b+1):a.substr(b+1,c-b-1)+"&"+a.substr(c+1);return a.split("&")}function _esc(a){return window.encodeURIComponent?encodeURIComponent(a):escape(a)}function _unesc(a){return window.decodeURIComponent?decodeURIComponent(a):unescape(a)}
function _argsUrl(a){var b={};a=ig_f(a);for(var c=0;c<a.length;c++){var d=a[c].indexOf("=");if(d!=-1){var e=a[c].substring(0,d);d=a[c].substring(d+1);d=d.replace(/\+/g," ");b[e]=_unesc(d)}}return b};var ig_aa={domload:1,xsetpdone:1,moduleedit:1,modulesocialedit:1,modulecanceledit:1,moduledelete:1,moduleundelete:1,modulezip:1,moduleunzip:1,modulemaximize:1,moduleunmaximize:1,moduledragstart:1,moduledragend:1,moduletitleclick:1,load:1,unload:1,resize:1},ig_g={},ig_ba={dragstart:1,dragend:1,titleclick:1,edit:1,socialedit:1,canceledit:1,"delete":1,undelete:1,zip:1,unzip:1,maximize:1,unmaximize:1};
function ig_ca(a){if(a.hasOwnProperty&&a.hasOwnProperty("ig_event_hashcode_"))return a.ig_event_hashcode_;a.ig_event_hashcode_||(a.ig_event_hashcode_=++ig_h.bf);return a.ig_event_hashcode_}function ig_da(a){return"builtin_"+a}function ig_ea(a,b){if(a.indexOf&&a.indexOf("m_")==0)a=a.substring(2);return"builtin_m"+a+"_"+b}function ig_fa(a,b){return"builtin_"+ig_h.Le(a)+"_"+b}function ig_ga(a){return"custom_"+a}
function ig_ha(){for(var a in ig_h.d){for(var b=0;b<ig_h.d[a].length;b++)delete ig_h.d[a][b];if(a in ig_h.wa){var c=ig_h.wa[a];b=c[0];var d=c[1];c=c[2];if(b.removeEventListener)b.removeEventListener(d,c,ig_b);else b.detachEvent&&b.detachEvent("on"+d,c);delete ig_h.wa[a]}}ig_g={}}function ig_ia(a,b,c){for(c=c;c<b.length;c++)a[a.length]=b[c];return a}function ig_ja(a,b){if(a in ig_h.d)for(var c=0;c<ig_h.d[a].length;c++)if(ig_h.d[a][c]===b){ig_h.d[a][c]=ig_;return ig_a}return ig_b}
function ig_ka(a){if(a in ig_h.d)for(var b=0;b<ig_h.d[a].length;b++)if(ig_h.d[a][b]){for(var c=[],d=1;d<arguments.length;d++)c[c.length]=arguments[d];ig_h.d[a][b].apply(this,c)}}function ig_la(a,b){if(!(a in ig_h.Lg))throw Error("Unsupported event type: "+a);if(a=="load"&&window.ig_latency_v2)_IG_AddCustomEventHandler("ifr_aft",b);else{a=ig_h.cb(a);a in ig_h.d||(ig_h.d[a]=[]);ig_h.d[a][ig_h.d[a].length]=b;return ig_h.d[a].length}}
function ig_ma(a,b,c){if(!(b in ig_h.Mg))throw Error("Unsupported module event type: "+b);a=ig_h.db(a,b);a in ig_h.d||(ig_h.d[a]=[]);ig_h.d[a][ig_h.d[a].length]=c}
function ig_na(a,b,c){var d=ig_h.ic(a,b);if(!(d in ig_h.d)){ig_h.d[d]=[];var e=function(f){if(!f)f=window.event;ig_h.Ma.apply(a,[d,f])};if(a.addEventListener)a.addEventListener(b,e,ig_b);else if(a.attachEvent)a.attachEvent("on"+b,e);else throw Error("Object {"+a+"} does not support DOM events.");ig_h.wa[d]=[a,b,e]}e=ig_h.d[d].length;if(a===window&&b=="unload"&&e>0){ig_h.d[d][e]=ig_h.d[d][e-1];ig_h.d[d][e-1]=c}else if(ig_g[b])setTimeout(c,10);else ig_h.d[d][e]=c}
function ig_oa(a,b){a=ig_h.bb(a);a in ig_h.d||(ig_h.d[a]=[]);ig_h.d[a][ig_h.d[a].length]=b}function ig_pa(a,b){a=ig_h.cb(a);return ig_h.Ja(a,b)}function ig_qa(a,b,c){a=ig_h.db(a,b);return ig_h.Ja(a,c)}function ig_ra(a,b,c){a=ig_h.ic(a,b);return ig_h.Ja(a,c)}function ig_sa(a,b){a=ig_h.bb(a);return ig_h.Ja(a,b)}
function ig_ta(a){var b=a=="load"||a=="domload",c=ig_b;if(b){(c=ig_g[a])||_IG_TriggerCustomEvent(a+"_start");ig_g[a]=ig_a}var d=ig_h.V([ig_h.cb(a)],arguments,1);ig_h.Ma.apply(window,d);b&&!c&&_IG_TriggerCustomEvent(a+"_end")}function ig_ua(){var a=ig_h.V([],arguments,0);setTimeout(function(){ig_h.wd.apply(window,a)},0)}function ig_va(a,b){var c=ig_h.V([ig_h.db(a,b)],arguments,2);ig_h.Ma.apply(window,c)}
function ig_wa(){var a=ig_h.V([],arguments,0);setTimeout(function(){ig_h.Kb.apply(window,a)},0)}function ig_xa(a){var b=ig_h.V([ig_h.bb(a)],arguments,1);ig_h.Ma.apply(window,b)}function ig_ya(){var a=ig_h.V([],arguments,0);setTimeout(function(){ig_h.ud.apply(window,a)},0)}function ig_i(a,b){switch(a){case "delete":case "undelete":case "edit":case "socialedit":case "canceledit":case "zip":case "unzip":case "maximize":case "unmaximize":ig_wa(b,a);ig_ua("module"+a,b);break}}
function _IG_delayScript(a,b){function c(){clearTimeout(d);_IG_RemoveEventHandler("load",c);setTimeout(a,0)}var d;b=!isNaN(b)&&b||1E4;d=setTimeout(c,b);_IG_AddEventHandler("load",c)}
var ig_h={bf:0,d:{},wa:{},Lg:ig_aa,Mg:ig_ba,Le:ig_ca,cb:ig_da,db:ig_ea,ic:ig_fa,bb:ig_ga,re:ig_ha,V:ig_ia,Ja:ig_ja,Ma:ig_ka,Ud:ig_la,cc:ig_ma,Td:ig_na,Sd:ig_oa,bg:ig_pa,fd:ig_qa,Zf:ig_ra,Yf:ig_sa,wd:ig_ta,Kb:ig_va,ud:ig_xa,Tg:ig_ua,vd:ig_wa,Sg:ig_ya},_IG_AddEventHandler=ig_h.Ud,_IG_AddModuleEventHandler=ig_h.cc,_IG_AddGadgetEventHandler=ig_h.cc,_IG_AddDOMEventHandler=ig_h.Td,_IG_AddCustomEventHandler=ig_h.Sd,_IG_RemoveEventHandler=ig_h.bg,_IG_RemoveModuleEventHandler=ig_h.fd,_IG_RemoveGadgetEventHandler=
ig_h.fd,_IG_RemoveDOMEventHandler=ig_h.Zf,_IG_RemoveCustomEventHandler=ig_h.Yf,_IG_TriggerEvent=ig_h.wd,_IG_TriggerModuleEvent=ig_h.Kb,_IG_TriggerGadgetEvent=ig_h.Kb,_IG_TriggerCustomEvent=ig_h.ud,_IG_TriggerDelayedEvent=ig_h.Tg,_IG_TriggerDelayedModuleEvent=ig_h.vd,_IG_TriggerDelayedGadgetEvent=ig_h.vd,_IG_TriggerDelayedCustomEvent=ig_h.Sg;_IG_AddDOMEventHandler(window,"unload",ig_h.re);_IG_AddDOMEventHandler(window,"load",function(){_IG_TriggerEvent("load")});
_IG_AddDOMEventHandler(window,"unload",function(){_IG_TriggerEvent("unload")});_IG_AddDOMEventHandler(window,"resize",function(){_IG_TriggerEvent("resize")});function _IG_RegisterOnloadHandler(a){_IG_AddEventHandler("domload",a)}function _IG_LoadLibraryDeferred(a,b){_IG_RegisterOnloadHandler(function(){_IG_LoadScript(a,b)})}_exportSymbols("google.gadgets.Events",["addHandler",_IG_AddEventHandler,"removeHandler",_IG_RemoveEventHandler,"addOnloadHandler",_IG_RegisterOnloadHandler]);
function _IG_RegisterMaximizeHandler(a,b){_IG_AddModuleEventHandler(a,"unmaximize",function(){b(ig_b)});_IG_AddModuleEventHandler(a,"maximize",function(){b(ig_a)})};function _gel(a){return document.getElementById(a)}function _gelstn(a,b){b=b||document;if(a=="*"&&b.all)return b.all;return b.getElementsByTagName?b.getElementsByTagName(a):[]}function _gelsbyregex(a,b,c){a=_gelstn(a,c);c=[];for(var d=0,e;e=a[d];++d)b.test(e.id)&&c.push(e);return c}function _trim(a){return a.replace(/^\s*|\s*$/g,"")}function _jesc(a){return a.replace(/\\/g,"\\\\").replace(/'/g,"\\'").replace(/"/g,'\\"')}
function _toggle(a){if(a)if(a.style.display==""||a.style.display=="block")a.style.display="none";else if(a.style.display=="none")a.style.display="block"}function _hesc(a){return a.replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")}function _striptags(a){return a.replace(/<\/?[^>]+>/gi,"")}function _ig_gmid_(a){return a.split("_")[2]}
function _showUserPrefs(a,b){if(b){ig_j("m_"+a+"_editbox","none");ig_j("m_"+a+"_aclbox","block");ig_i("socialedit","m_"+a)}else{ig_j("m_"+a+"_editbox","");ig_j("m_"+a+"_aclbox","none");ig_i("edit","m_"+a)}if(a=_gel("m_"+a))a.className="modbox_e"}function _closeUserPrefs(a){ig_j("m_"+a+"_editbox","none");ig_j("m_"+a+"_aclbox","none");if(a=_gel("m_"+a))a.className="modbox"}function _min(a,b){return a<b?a:b}function _max(a,b){return a>b?a:b}
function _IG_LoadScript(a,b){_sendx(a,function(c){window.eval(c);eval(b)})}function _IG_LoadScriptCallback(a,b){_sendx(a,function(c){window.eval(c);b&&b()})}function _IG_LoadScriptXDomain(a,b,c){function d(){eval(b)?c():setTimeout(function(){d()},100)}var e=document.createElement("script");e.src=a;_gelstn("head")[0].appendChild(e);b&&d()}
function _IG_LoadCss(a){var b=_gelstn("head")[0];if(!b)throw new Error("Document is missing <head> element.  Failed to load CSS.");var c=document.createElement("style");c.type="text/css";if(c.styleSheet)c.styleSheet.cssText=a;else c.appendChild(document.createTextNode(a));b.insertBefore(c,b.firstChild)}function _log(a){a="/ig/log?msg="+_esc(a);_sendx(a)}
function _sendx(a,b,c,d){var e=ig_k();e.open(d?"POST":"GET",a,ig_a);if(b)e.onreadystatechange=function(){if(e.readyState==4)b(c&&e.responseXML?e.responseXML:e.responseText)};e.send(d||ig_)}function ig_k(){var a=ig_;if(window.ActiveXObject)(a=new ActiveXObject("Msxml2.XMLHTTP"))||(a=new ActiveXObject("Microsoft.XMLHTTP"));else if(window.XMLHttpRequest)a=new XMLHttpRequest;return a}
var _et="",_brand="",_bmod="",_source="",_ae="",_pid="",_authpath="",_prefid="",_setp_url="/ig/setp",_hl="",_old_html=ig_a,_use_old_feed_styles=ig_a,ig_l=ig_,ig_m=ig_;function ig_n(a,b,c){var d=a.elements[b];if(d)d.value=c;else{d=document.createElement("input");d.type="hidden";d.name=b;d.value=c;a.appendChild(d)}}var ig_o=ig_;function _args(){ig_o||(ig_o=_argsUrl(document.location.href));return ig_o}function _IG_isIE(){return/msie/i.test(navigator.userAgent)}
function _qs(a){var b={pid:1,host:1,gl:1,hl:1,enable_flag:1,e:1,expid:1};a=a||_args();var c=["?"];for(var d in a)b[d]&&c.push(d,"=",_esc(a[d]),"&");return c.join("")}var ig_za=/^([^?#]+)(?:\?([^#]*))?(#.*)?/;function ig_p(a,b){a=ig_za.exec(a);var c=[a[1],"?",a[2]];c.push(a[2]?"&":"",b.join("&"),a[3]);return c.join("")}function ig_Aa(a){var b={url:document.location,et:_et,brand:_brand,bmod:_bmod,source:_source,ae:_ae,pid:_pid,ap:_authpath,prefid:_prefid};for(var c in b)b[c]&&ig_n(a,c,b[c])}
function _submit_form(a,b){a.action=_setp_url+_qs()+b;a.method="get";ig_Aa(a);a.submit()}function _fsetp(a,b,c){a.action=_setp_url;a.method="get";ig_Aa(a);ig_n(a,"m_"+b+"_t",c);c=_args();b=c.host;c=c.hl;b&&ig_n(a,"host",b);c&&ig_n(a,"hl",c);return ig_a}var ig_q=[],ig_r=ig_b;
function ig_Ba(){var a;a=[["et",_et],["pid",_pid],["ap",_authpath],["brand",_brand],["bmod",_bmod],["source",_source],["ae",_ae],["prefid",_prefid]];for(var b=[],c=0;c<a.length;++c)if(a[c].length==2){var d=a[c][0],e=a[c][1];e!=ig_&&e!=""&&b.push(d+"="+e)}return a=b.join("&")}function ig_Ca(){if(ig_q.length==0)ig_r=ig_b;else{ig_r=ig_a;var a=_setp_url+_qs()+ig_Ba(),b=ig_q.join("&");ig_q=[];var c=a.length+b.length>=1800;if(c)_sendx(a,ig_Da,ig_b,b);else{a+="&"+b;_sendx(a,ig_Da,ig_b,ig_)}}}
function ig_Da(){_IG_TriggerDelayedEvent("xsetpdone");ig_Ca()}function _xsetp(a){ig_q.push(a);ig_r||ig_Ca()}function _xsetp_is_done(){return ig_q.length==0&&ig_r==ig_b}function _dlsetp(a,b){b||(b=_esc(document.location));document.location=_setp_url+_qs()+ig_Ba()+"&url="+b+"&"+a}function _removeTabParam(a){a=a.split("#");a[0]=a[0].replace(/([?&])t=[^&#]*([&#]|$)/g,"$1");a[0]=a[0].replace(/[?&]$/,"");return a.join("#")}function _select_tab(a,b){b=b||ig_Ea();ig_s(b+_qs()+"t="+a)}
function _select_tab_and_log(a,b){_sendx("/ig/ui?xp=v2&action=selectTab&t="+a);_select_tab(a,b)}function _select_gadget_and_log(a,b,c){c=c||ig_Ea();_sendx("/ig/ui?xp=v2&action=maximizeMod&from=selectMod&mid="+b);window.ih?ig_s(c+_qs()+"t="+a+"&g="+b):ig_s(c+_qs()+"t="+a+"#max"+b)}function ig_Ea(a){a=a||document.location.pathname;if(a=="/")return"/ig";return"/"+a.split("/")[1]}function ig_s(a){window.location.href=a}function ig_j(a,b){if(a=_gel(a))a.style.display=b}
_exportSymbols("",["setDisplayStyle",ig_j]);function _ssbc(a,b,c){for(var d=_gelstn("*"),e=0,f;f=d[e];e++)if(f.className==a)f.style[b]=c}function _findPos(a){for(var b=0,c=0;a!=ig_;){b+=a.offsetLeft;c+=a.offsetTop;a=a.offsetParent}return[b,c]}function _getGadgetContainer(a){var b=_gel("m_"+a+"_b");if(!b){b=_gel("remote_"+a);if(!b)b=document.body}return b}function _appendMaxAgeParameter(a,b){var c=/[?&]$/.test(a);return a+(c?"":"&")+"max_age="+b+(c?"&":"")}
function _getStyle(a,b){if(typeof a.currentStyle!="undefined")a=a.currentStyle;else if(document.defaultView.getComputedStyle!="undefined")a=document.defaultView.getComputedStyle(a,ig_);else return"";return a[b]}function ig_t(){for(var a=_IG_MD,b=0;b<arguments.length;++b){a=a[arguments[b]];if(a==ig_)return ig_}return a}function _bidi_span_wrap(a,b){return _bidi_span_wrap_html(_hesc(a),b)}
function _bidi_span_wrap_html(a,b){if(b=="rtl")return"<span dir=rtl>"+a+"</span>&lrm;";return a}
function _bidi_unicode_wrap(a,b){if(b=="rtl")return"\u202b"+a+"\u202c\u200e";return a}_exportSymbols("google.gadgets.Util",["args",_args]);_exportSymbols("",["addParamPairsToUrl",ig_p,"xmlhttp",ig_k]);if(!window.FLAG_isInSplitJS)window.FLAG_isInSplitJS=ig_b;function ig_u(a){this.D=[];this.sb=a;this.Ba("_IG_DD_open");this.Ba("_IG_hoverHeader");this.Ba("_IG_hoverModule");this.S("_IG_DD_create");this.S("_IG_DD_init");this.S("_IG_initDrag");this.S("_IG_PushHistory");this.S("_IG_PU_MakeDialogButton")}ig_u.prototype.ad=ig_b;ig_u.prototype.rc=ig_b;ig_u.Dd=1E4;ig_c=ig_u.prototype;
ig_c.S=function(a){if(this.sb){var b=window,c=a.lastIndexOf(".");if(c>=0){b=ig_d(a.substring(0,c));a=a.substring(c+1)}if(b[a]&&!b[a].Oc)throw new Error(a+" is already defined.");b[a]=this.ne(a)}};ig_c.Ba=function(a){if(this.sb){var b=window,c=a.lastIndexOf(".");if(c>=0){b=ig_d(a.substring(0,c));a=a.substring(c+1)}b[a]=function(){}}};ig_c.ne=function(a){var b=this;function c(){for(var d=[],e=0;e<arguments.length;e++)d.push(arguments[e]);b.D.push([a,this,d])}c.Oc=ig_a;return c};
ig_c.ec=function(){if(this.D.length!=0){var a=this.D.shift(),b=a[0],c=a[1];a=a[2];try{var d=b instanceof Function?b:window[b];d.apply(c,a)}catch(e){}if(this.D.length>0){var f=this;setTimeout(function(){f.ec()},0)}else{this.rc=ig_a;this.$f()}}};
ig_c.je=function(){for(var a=[],b=0;b<this.D.length;b++){var c=this.D[b][0];if(!(c instanceof Function))if(window[c].Oc){a.push(c);this.D.splice(b,1);b--}}var d=this;setTimeout(function(){d.ec()},0);if(a.length>0)throw new Error("The following functions were not found in the post load file: "+a.join(", "));};ig_c.$f=function(){for(var a=_gelstn("*"),b=0;b<a.length;b++){var c=a[b];c.className&&c.className.split&&ig_e(c,"disabled",ig_)}};
ig_c.wf=function(a,b){b=this.vf(b);_IG_AddEventHandler(a,b);setTimeout(b,ig_u.Dd)};ig_c.vf=function(a){var b=this;return function(){if(!b.ad){_IG_LoadScriptXDomain(a,"window._IG_DD_position",function(){b.je()});b.ad=ig_a}}};ig_c.fe=function(a){this.rc||!this.sb?a():this.D.push([a,ig_,[]])};var ig_v;ig_v||(ig_v=new ig_u(window.FLAG_isInSplitJS));function _IG_callPostLoad(a){ig_v.fe(a)}function _IG_deferFunction(a){ig_v.S(a)}function _IG_ignoreFunction(a){ig_v.Ba(a)}
function _IG_loadPostloadJS(a,b){ig_v.wf(a,b)};function ig_w(a,b){function c(){}c.prototype=a.prototype;b.prototype=new c}function _ListApp(a,b,c){this.items=a;this.va=[];this.Sc=b;this.ia=c;this.Ya="m_"+c+"_App";this.vc=_gel("m_"+c+"_disp");this.Gg=ig_a;this.Y=_gel("m_"+c+"_val");this.L=_gel("m_"+c+"_name");if(!this.L)this.L=this.Y;if(this.L){this.pc=this.L.value;this.qc=this.Y.value}this.bd=[].concat(this.items)}ig_c=_ListApp.prototype;ig_c.reset=function(){this.items=[].concat(this.bd);this.va=[];this.refresh()};ig_c.sort=function(a,b){return a.ab(b)};
ig_c.Wf=function(){var a="";if(_old_html)a="<table cellspacing=0 cellpadding=0 border=0>";for(var b="",c=this.items,d=0;d<c.length;d++)if(c[d]){a+=_old_html?"<tr><td nowrap><font size=-1>"+c[d].pb()+'</font></td><td><a href="#" onclick="'+this.Ya+"._del("+d+');return false"><img src="/ig/images/x.gif" width=16 height=13 border=0></a></td></tr>':'<a href="#" onclick="'+this.Ya+"._del("+d+');return false" class="delbox listdelbox"></a>'+c[d].pb()+'<div class="c"></div>';if(parseInt(c[d].Wa,10)<0)b+=
c[d].Oa(d)}else{this.items.splice(d,1);d--}c=this.va;var e="";for(d=0;d<c.length;d++)if(parseInt(c[d].Wa,10)>=0)e+=","+c[d].Wa;a+=this.Ec(b,e);return a};ig_c.Ec=function(a,b){var c="<input type=hidden name=m_"+this.ia+'_del value="'+b+'"><input type=hidden name=m_'+this.ia+'_add value="'+a+'">';if(_old_html)c="</table><input type=hidden name=m_"+this.ia+'_del value="'+b+'"><input type=hidden name=m_'+this.ia+'_add value="'+a+'">';return c};
ig_c.refresh=function(){this.Gg&&this.items.sort(this.sort);this.vc.innerHTML="<font size=-1>"+this.Wf()+"</font>"};ig_c.add=function(a,b){a||(a=_trim(this.L.value));b||(b=_trim(this.Y.value));a=new this.Sc(a,b,-1);if(a.vb()){this.items[this.items.length]=a;this.refresh();this.L.value=this.pc;this.Y.value=this.qc}};ig_c._del=function(a){this.va[this.va.length]=this.items[a];this.items.splice(a,1);this.refresh()};
function _PrefListApp(a,b,c,d,e){var f=typeof c=="string"?[]:c;d=new _ListApp(f,d,e);for(var h in d)this[h]=d[h];typeof c=="string"&&this.Rf(c);this.Vf=a;this.sh=b;this.Ya="m_"+e+"_"+a+"_App";this.vc=_gel("m_"+e+"_"+a+"_disp");this.L=this.Y=_gel("m_"+e+"_"+a+"_val");this.qc=this.pc="";this.Ec=_PrefListApp_get_tail}function _PrefListApp_get_tail(){var a="</table>";_gel("m_"+this.ia+"_"+this.Vf).value=this.Ig();return a}
_PrefListApp.prototype.Rf=function(a){if(a.length!=0){a=a.length>0?a.split("|"):[];for(var b=0;b<a.length;++b)a[b]=a[b].replace(/%7C/g,"|");a=a;b=[];for(var c=0;c<a.length;c++){var d=new this.Sc(a[c],a[c],-1);b[b.length]=d}this.items=b;this.bd=[].concat(b)}};_PrefListApp.prototype.Ig=function(){for(var a=[],b=0;b<this.items.length;b++)a[a.length]=this.items[b].J;a=a;if(b=a.length&&a.join){b=[];for(var c=0;c<a.length;++c)b.push(a[c].replace(/\|/g,"%7C"));a=b.join("|")}else a=a;return a};
function _ListItem(a,b,c){this.q=a;this.J=b;this.Wa=c}_ListItem.prototype.vb=function(){return this.q!=""};_ListItem.prototype.ab=function(){return 0};_ListItem.prototype.pb=function(){return _hesc(this.q)};_ListItem.prototype.Oa=function(){return"&"+_esc(this.q)+"="+_esc(this.J)};function _BMListItem(a,b,c){_ListItem.call(this,a,b,c)}ig_w(_ListItem,_BMListItem);ig_c=_BMListItem.prototype;ig_c.vb=function(){return _ListItem.prototype.vb.call(this)&&this.q!="http://"};
ig_c.mb=function(){if(this.J)return this.J;else{var a=this.q;if(a.indexOf("http://")==0)a=a.substring(7);if(a.indexOf("www.")==0)a=a.substring(4);return a}};ig_c.pb=function(){return'<a href="'+this.q+'" target=bmwindow>'+_hesc(this.mb())+"</a>"};ig_c.Oa=function(a){return"&b"+a+"="+_esc(this.q)+"&t"+a+"="+_esc(this.J)};ig_c.ab=function(a){var b=this.mb().toUpperCase();a=a.mb().toUpperCase();if(b==a)return 0;return b<a?-1:1};function _WthrListItem(a,b,c){_ListItem.call(this,a,b,c)}
ig_w(_ListItem,_WthrListItem);_WthrListItem.prototype.Oa=function(){var a="&"+_esc(this.q);if(this.J)a+="="+_esc(this.J);return a};function _FListItem(a,b,c,d){_ListItem.call(this,a,b,c);this.qa=d||0}ig_w(_ListItem,_FListItem);_FListItem.prototype.Oa=function(){return"&"+_esc(this.q)};_FListItem.prototype.ab=function(a){var b=this;if(b.qa<a.qa)return-1;if(b.qa>a.qa)return 1;b=b.q.toUpperCase();a=a.q.toUpperCase();if(b<a)return-1;if(b>a)return 1;return 0};function _edit(a,b){function c(){b&&b();_sendx("/ig/ui?action=editsettings&m="+a);ig_i("edit","m_"+a)}var d=ig_Fa[a];if(d){d();c()}else _IG_LL_load("m_"+a+"_editbox",{mid:a},function(){_showUserPrefs(a,ig_b);c()});return ig_b}var ig_Fa={};function _IG_AddCustomEditHandler(a,b){ig_Fa[a]=b}function _cedit(a){_closeUserPrefs(a);var b=_gel("m_"+a+"_form");if(b){b.reset();_sendx("/ig/ui?action=canceledit&m="+a);ig_i("canceledit","m_"+a);return ig_b}}
function _uhc(a,b,c){b="m_"+a+"_"+b;var d=_gel(b);if(!d){d=document.createElement("INPUT");d.type="hidden";d.disabled=ig_a;d.name=b;_gel("m_"+a+"_form").appendChild(d)}d.value=c;d.disabled=ig_b}function _confirmDel(a,b,c,d){var e=_bidi_unicode_wrap(_get_module_title(a),_get_module_title_dir(a));d=d.replace(/MODULE_TITLE/,e);confirm(d)&&_del(a,b,c)}
function _get_module_title(a){if(typeof a=="object")a=a.id.replace("m_","");else if(typeof a=="string")a=a.replace("m_","");if(typeof _IG_MD!="undefined")return _IG_MD.m[a].ti;else return(a=_gel("m_"+a+"_title"))?_striptags(a.innerHTML):""}function _get_module_title_dir(a){if(typeof a=="object")a=a.id.replace("m_","");else if(typeof a=="string")a=a.replace("m_","");if(typeof _IG_MD!="undefined")return _IG_MD.m[a].ti_dir}
function _get_all_modules(){var a,b=_gelsbyregex("DIV",/^c_[0-9]+$/);a=[];for(var c=0;c<b.length;c++)b[c].style.display!="none"&&a.push(b[c]);a=a;b=[];c=/^m_[0-9]+$/;for(var d=0;d<a.length;d++){b[d]=[];for(var e=b[d],f=0;f<a[d].childNodes.length;f++){var h=a[d].childNodes[f];h.tagName=="DIV"&&h.style.display!="none"&&h.id&&c.test(h.id)&&e.push(h)}}if(window.gadgets&&window.gadgets.views&&window.gadgets.views.ViewManager&&window.gadgets.views.ViewManager.getCurrentMaxId)(a=window.gadgets.views.ViewManager.getCurrentMaxId())&&
b.length>0&&a&&b[0].unshift(_gel("m_"+a));return b}var ig_x=ig_b;function _del_is_done(){return _xsetp_is_done()&&ig_x}
function _del(a,b,c){ig_x=ig_b;_xsetp("m_"+a+"_enab=0&m_"+a+"_t="+b);if(b=_gel("undel_msg")){_gel("undel_title").innerHTML="&quot;"+_bidi_span_wrap(_get_module_title(a),_get_module_title_dir(a))+"&quot; ";b.style.display="block";ig_j("undo_msg","none");ig_j("undo_restore_msg","none")}ig_j("m_"+a,"none");ig_l=a;ig_m=c;ig_j(c,"");_mod=ig_a;ig_i("delete","m_"+a);ig_x=ig_a;return ig_b}
function _undel(){if(ig_l!=ig_){var a="m_"+ig_l,b=_gel(a);if(b){ig_j(a,"block");_xsetp("undel")}ig_j("undel_msg","none");ig_m!=ig_&&ig_j(ig_m,"none");ig_m=ig_l=ig_;ig_i("undelete",a)}}function _isModuleZipped(a){if(a=_gel("m_"+a+"_b"))return a.style.display=="none";return ig_b}
function _zm(a,b,c){var d=_gel("m_"+a+"_b");if(d){var e=!_isModuleZipped(a);d.style.display=e?"none":"block";if(d=_gel("m_"+a+"_zippy"))d.className=e?d.className.replace(/minbox/,"maxbox"):d.className.replace(/maxbox/,"minbox");c=c?"mmz":"mz";_xsetp(c+"="+a+":"+(e?"1":"0")+"&t="+b);ig_i(e?"zip":"unzip",a)}return ig_b}var _uli,_pnlo,_mpnlo,_pl,_mod,_cbp=ig_b,ig_Ga=ig_b,_table=ig_,_tabs=ig_;
function _upc(){var a=[];_cbp||(a[a.length]=["medit","display",_uli?"":"none"]);a[a.length]=["panelo","display",_pnlo?"":"none"];a[a.length]=["panelc","display",_pnlo?"none":""];if(_mod){a[a.length]=["unmod","display","none"];a[a.length]=["mod","display",""]}else{a[a.length]=["mod","display","none"];a[a.length]=["unmod","display",""]}a=a;for(var b=_gelstn("*"),c=0,d;d=b[c];c++)for(var e=0;e<a.length;e++)if(d.className==a[e][0])d.style[a[e][1]]=a[e][2];_IG_callPostLoad(_init_drag_drop)}
function _init_drag_drop(){if(_pl)if(_cbp||_uli)if(!ig_Ga&&!_mpnlo){_IG_TriggerCustomEvent("initdrag",_table,_tabs);ig_Ga=ig_a}}var ig_y=0;
function _tp(a){ig_y>0&&clearInterval(ig_y);_pnlo=a;_mod=ig_a;_xsetp("pnlo="+(a?1:0));_upc();var b=_gel("cpnl"),c=_gel("cpnlc"),d=b.offsetWidth,e,f;if(a){e=c.offsetWidth;f="visible";ig_j("ehdr","");ig_j("nhdr","none")}else{e=1;f="hidden";ig_j("ehdr","none");ig_j("nhdr","")}b.style.overflow="hidden";a=100;var h=10,g=0;ig_y=setInterval(function(){var l=g/h,k=d+(e-d)*l;b.style.width=k+"px";g++;if(l>=1){clearInterval(ig_y);ig_y=0;b.style.width=e+"px";b.style.overflow=f}},a/h);return ig_b}
function _ts(a,b){a=_gel(a+b);if(a.className=="mlist_open"){a.className="mlist_closed";a="pnlsc"}else{a.className="mlist_open";a="pnlso"}_xsetp(a+"="+_esc(b));return ig_b}function _add_m(a,b){_dlsetp(a,b)}function _add_m_confirm(a,b,c){confirm(b)&&_add_m(a,c)}function _add_f(a){_add_m("n_25="+_esc("url="+_esc(a)))}var ig_Ha=/^_add_m(_confirm)?\(\"[^"]+\"(, *\"[^"]+\")?\)$/,ig_z=ig_a;function _find_feed_is_done(){return ig_z}
function _find_feed(a){ig_z=ig_b;var b="acd";if(!a){var c=_gelstn("div");if(c)for(var d=0,e;e=c[d];d++)e.id&&e.id.indexOf("ps")==0&&e.className=="mlist_open"&&_ts("ps",e.id.substring(2));if(_gel("add_custom"))a=_gel("add_custom").value}if(!a||a==""){b="advdsrch";a=_gel("add_advd").value}ig_j("ffresults","none");ig_j("ffloading","block");_sendx("/ig/feeds"+_qs()+"q="+_esc(a)+"&page="+_esc(b),ig_Ia);return ig_b}
function ig_Ia(a){ig_j("ffloading","none");ig_j("ffresults","block");if(a.length>0&&a.charAt(0)=="<"){if(_gel("ffresults"))_gel("ffresults").innerHTML=a}else{a.match(ig_Ha)!=ig_;eval(a)}ig_z=ig_a}function _add_remote_module(a,b,c){_sendx("/ig/feeds"+_qs()+"module=1&q="+_esc(a),function(d){b();d=d;var e=c,f=/_add_m_confirm\((\"[^"]+\"),\s*(\"[^"]+\")(,\s*\"[^"]+\")?\)/,h=/^alert\(\"[^"]+\"\)$/;if(d.match(ig_Ha)!=ig_||d.match(h)!=ig_){if(e)d=d.replace(f,"_add_m($1$3)");eval(d)}});return ig_b}
function ig_A(a){if(!a)a=document.body;return a.scrollHeight>a.offsetHeight?a.scrollHeight:a.offsetHeight}function ig_B(){return self.pageYOffset?self.pageYOffset:document.documentElement&&document.documentElement.scrollTop?document.documentElement.scrollTop:document.body.scrollTop}function _closePromoBox(a){_toggle(_gel("promo"+a));_xsetp("gpc="+a+":-1")}_exportSymbols("",["pageHeight",ig_A,"scrollTop",ig_B]);var ig_C={},ig_Ja={};
function _place(a,b){var c=ig_Ja[a];if(c)c(b);else{ig_C[a]||(ig_C[a]=[]);ig_C[a].push(b)}}function _register_place(a,b){ig_Ja[a]=b;var c=ig_C[a];if(c){for(var d=0;d<c.length;d++)b(c[d]);ig_C[a]=ig_}};function _reload(a,b){var c=a-(new Date).getTime();if(c>1E3)setTimeout("_reload("+a+")",c);else if(b)document.location.replace(ig_Ka(document.location.href,document.location.pathname));else{document.cookie="IGREL=1";document.location.replace(document.location.href.split("#")[0])}}var ig_La=/^([^?#]+)(?:\?([^#]*))?(#.*)?/;function ig_Ka(a,b){var c=ig_La.exec(a),d=c[1];if(b=="/")d+="ig";d+="?";if(b=c[2])d+=b;if(!_argsUrl(a).refresh){if(b)d+="&";d+="refresh=1"}return d}
var ig_D={kb:0,td:1800,Ab:ig_,zb:ig_,Xa:ig_a,ea:ig_,yd:ig_,fc:600,na:function(){ig_D.kb=(new Date).getTime()+ig_D.td*1E3},Qf:function(){if((new Date).getTime()>ig_D.kb)window.gTalkNotifier&&window.gTalkNotifier._isAnyMoleOpen&&window.gTalkNotifier._isAnyMoleOpen()?ig_D.na():_testConnection(function(){_reload(ig_D.kb,ig_D.yd)},ig_D.na)},Cb:function(a){ig_D.na();ig_D.Ab&&ig_D.Ab(a)},Bb:function(a){ig_D.na();ig_D.zb&&ig_D.zb(a)}};
function _IG_disable_refresh_cycle(){ig_D.Xa=ig_b;_IG_suspend_refresh_cycle()}function _IG_suspend_refresh_cycle(){if(ig_D.ea!=ig_){clearInterval(ig_D.ea);ig_D.ea=ig_}}function _IG_restart_refresh_cycle(){!ig_D.Xa||ig_D.ea!=ig_||ig_Ma()}
function _IG_start_refresh_cycle(a,b,c){if(ig_D.Xa){ig_D.Ab=document.onmousedown;ig_D.zb=document.onkeyup;ig_D.td=a;ig_D.fc=b;if(c)ig_D.yd=c;if(document.addEventListener){document.addEventListener("keyup",ig_D.Bb,ig_b);document.addEventListener("mousedown",ig_D.Cb,ig_b)}else if(document.attachEvent){document.attachEvent("onkeyup",ig_D.Bb);document.attachEvent("onmousedown",ig_D.Cb)}else{document.onkeyup=ig_D.Bb;document.onmousedown=ig_D.Cb}ig_Ma()}}
function ig_Ma(){ig_D.na();ig_D.ea=setInterval(ig_D.Qf,ig_D.fc*1E3)}function _testConnection(a,b,c){var d=ig_k(),e="/ig/nop?t="+(new Date).getTime();c||(c=3500);d.open("GET",e,ig_a);d.onreadystatechange=function(){if(d.readyState==4&&a)if(200<=d.status&&d.status<300||d.status==1223){b=ig_;a()}};try{d.send(ig_)}catch(f){}function h(){if(b){a=ig_;b()}}setTimeout(h,c)};function _IG_GetCachedUrl(a,b){b=typeof b=="object"?b:{};var c=window.location.href,d="/ig/proxy?",e=/^http:\/\/[^\/]+\/ig\/ifr[?]/;if((e=e.exec(c))||c.indexOf("http://www.google.cn/ig/china")==0){if(window.location.host!="p.gmodules.com"&&_et)d+="et="+_esc(_et)+"&"}else d="http://p.gmodules.com/ig/proxy?";if(!isNaN(b.refreshInterval)&&b.refreshInterval>=0)d=_appendMaxAgeParameter(d,b.refreshInterval);return d+"url="+_esc(a)+"&log=1"}function _IG_GetImageUrl(a,b){return _IG_GetCachedUrl(a,b)}
function _IG_GetImage(a,b){var c=document.createElement("img");c.src=_IG_GetCachedUrl(a,b);return c};function _IG_Callback(a){var b=arguments;return function(){for(var c=[],d=0;d<arguments.length;d++)c[c.length]=arguments[d];for(d=1;d<b.length;d++)c[c.length]=b[d];a.apply(ig_,c)}};var _IG_Layouts={};_IG_Layouts._selectLayout=function(a){for(var b=_gel("edit_this_tab_form").edit_this_tab_selected_layout,c=0;c<b.length;c++){var d=b[c].value,e=_gel("edit_this_tab_layoutimg_"+d);if(d!=a){b[c].checked=ig_b;if(e.src.indexOf("_highlight")!=-1)e.src=e.src.substring(0,e.src.indexOf("_highlight"))+".gif"}else{b[c].checked=ig_a;if(e.src.indexOf("_highlight")==-1)e.src=e.src.substring(0,e.src.indexOf(".gif"))+"_highlight.gif"}}};var ig_E=function(){var a=ig_b,b=[],c=ig_,d=ig_;return{init:function(){},load:function(e,f,h){if(_gel(e))h(f);else{b.push({id:e,args:f,callback:h});if(!a)if(c){d(c,b);b=[]}else{_sendx("/ig/ui?action=lazy&id="+e,ig_,ig_b,ig_);if(!(c||a)){a=ig_a;_IG_LoadScript("/ig/ll"+window.location.search,"")}}}},xf:function(e,f){c=e;d=f;a=ig_b;d(c,b);b=[]},wh:function(){a=ig_b;b=[];d=c=ig_}}}(),_IG_LL_init=ig_E.init,_IG_LL_load=ig_E.load,_IG_LL_loaded=ig_E.xf;var ig_F=[];function _IG_isModuleInVisibleArea(a){var b=ig_B(),c,d=c=0;if(window.innerHeight){c=window.innerWidth;d=window.innerHeight}else if(document.documentElement&&document.documentElement.clientHeight){c=document.documentElement.clientWidth;d=document.documentElement.clientHeight}else if(document.body.clientHeight){c=document.body.clientWidth;d=document.body.clientHeight}c={width:c,height:d};c=c.height;d=parseInt(a.style.height,10);a=_findPos(a)[1];return a+d>b&&a<b+c}
function _IG_delayLoadGadget(a){ig_F.push(a)}function _IG_loadDelayLoadGadgets(){for(var a=0;a<ig_F.length;++a){var b=_gel("remote_iframe_"+ig_F[a].id);if(b){var c=b.getAttribute("src");if(c==ig_||c=="")b.src=ig_F[a].base_iframe_url}}};function _IG_MD_Generate(a){var b={t:{},dt:[],m:{},f:{}},c=a,d=b;if(c.t)for(var e=0;e<c.t.length;++e){var f=c.t[e];d.t[f.i]=f;d.t[f.i].m={}}c=a;d=b;if(c.f)for(e=0;e<c.f.length;++e){f=c.f[e];d.f[f.n]=f}c=a;d=b;if(c.m)for(e=0;e<c.m.length;++e){f=c.m[e];f.fa||(f.fa={});d.m[f.i]=f;var h=d.t[f.t];if(h)h.m[f.i]=f}if(a.ct!=ig_&&b.t)b.ct=b.t[a.ct];a=a;c=b;if(a.dt)for(d=0;d<a.dt.length;++d)c.dt[d]=c.t[a.dt[d]];return b};var ig_G;
ig_G||(ig_G=function(){function a(k){return k<10?"0"+k:k}function b(k){e.lastIndex=0;return e.test(k)?'"'+k.replace(e,function(m){var o=g[m];if(typeof o==="string")return o;return"\\u"+("0000"+(+m.charCodeAt(0)).toString(16)).slice(-4)})+'"':'"'+k+'"'}function c(k,m){var o,r,j=f,s,i=m[k];if(i&&typeof i==="object"&&typeof i.toJSON==="function")i=i.toJSON(k);if(typeof l==="function")i=l.call(m,k,i);switch(typeof i){case "string":return b(i);case "number":return isFinite(i)?String(i):"null";case "boolean":case "null":return String(i);
case "object":if(!i)return"null";f+=h;s=[];if(typeof i.length==="number"&&!i.propertyIsEnumerable("length")){r=i.length;for(k=0;k<r;k+=1)s[k]=c(k,i)||"null";m=s.length===0?"[]":f?"[\n"+f+s.join(",\n"+f)+"\n"+j+"]":"["+s.join(",")+"]";f=j;return m}if(l&&typeof l==="object"){r=l.length;for(k=0;k<r;k+=1){o=l[k];if(typeof o==="string")if(m=c(o,i))s.push(b(o)+(f?": ":":")+m)}}else for(o in i)if(Object.hasOwnProperty.call(i,o))if(m=c(o,i))s.push(b(o)+(f?": ":":")+m);m=s.length===0?"{}":f?"{\n"+f+s.join(",\n"+
f)+"\n"+j+"}":"{"+s.join(",")+"}";f=j;return m}}Date.prototype.toJSON=function(){return this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z"};String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()};var d=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,e=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
f,h,g={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},l;return{stringify:function(k,m,o){m=m;o=o;var r;h=f="";if(typeof o==="number")for(r=0;r<o;r+=1)h+=" ";else if(typeof o==="string")h=o;if((l=m)&&typeof m!=="function"&&(typeof m!=="object"||typeof m.length!=="number"))throw new Error("JSON.stringify");return c("",{"":k})},parse:function(k,m){function o(j,s){var i,n,p=j[s];if(p&&typeof p==="object")for(i in p)if(Object.hasOwnProperty.call(p,i)){n=o(p,i);if(n!==
undefined)p[i]=n;else delete p[i]}return r.call(j,s,p)}var r=m;d.lastIndex=0;if(d.test(k))k=k.replace(d,function(j){return"\\u"+("0000"+(+j.charCodeAt(0)).toString(16)).slice(-4)});if(/^[\],:{}\s]*$/.test(k.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){k=eval("("+k+")");return typeof r==="function"?o({"":k},""):k}throw new Error("JSON.parse");}}}());
ig_G.parse=function(){var a=ig_G.parse;return function(b,c){try{return a(b,c)}catch(d){return ig_b}}}();function ig_Pa(a){var b=document.createElement("DIV");b.innerHTML="<iframe onload='this.pool_locked=false'></iframe>";var c=b.getElementsByTagName("IFRAME")[0];c.style.visibility="hidden";c.style.width=c.style.height="0px";c.style.border="0px";c.style.position="absolute";c.$c=a;this.o[this.o.length]=c;b.removeChild(c);return c}
function ig_Qa(a){if(a.match(/^http[s]?:\/\//)){var b=this;window.setTimeout(function(){for(var c=ig_,d=b.o.length-1;d>=0;d--){var e=b.o[d];if(e&&!e.$c){e.parentNode.removeChild(e);if(window.ActiveXObject){b.o[d]=ig_;b.o.splice(d,1)}else{e.$c=ig_a;c=e;break}}}c=c?c:b.oe(ig_a);c.src=a;document.body.appendChild(c)},0)}}function ig_Ra(){for(var a=0;a<this.o.length;a++){this.o[a].onload=ig_;this.o[a]=ig_}this.o.length=0;this.o=[]}
function ig_Sa(){for(var a=0;a<this.o.length;a++){var b=this.o[a];b&&b.parentNode.removeChild(b)}}function ig_Ta(){this.o=[];this.oe=ig_Pa;this.Lc=ig_Qa;this.clear=ig_Ra;this.wc=ig_Sa}function ig_Ua(a,b){_IFPC.ma[a]=b}function ig_Va(a){delete _IFPC.ma[a]}
function ig_Wa(a,b,c,d,e,f,h,g){if(!_IFPC.hb){var l=4095-d.length;l=parseInt(l/3,10);if(typeof h=="undefined")h=ig_a;if(g){h={s:b,a:c,f:"..",t:window._isk[a.split("_")[2]]};a=[a,"..",_IFPC.$a,1,1,encodeURIComponent(ig_G.stringify(h))].join("&");_IFPC.Aa.Lc(d+"#"+a)}else{c=c.slice(0);c.unshift(_IFPC.Xf(e));c.unshift(f);c.unshift(b);c.unshift(a);b=_IFPC.xc(c);c=parseInt(b.length/l,10);if(b.length%l>0)c+=1;for(e=0;e<c;e++){f=b.substr(e*l,l);f=[a,_IFPC.$a,c,e,f,h];_IFPC.Aa.Lc(d+"#"+_IFPC.xc(f))}}_IFPC.$a++}}
function ig_Xa(){_IFPC.ma={};_IFPC.P={};_IFPC.Aa.clear()}function ig_Ya(){if(!_IFPC.hb){_IFPC.hb=ig_a;_IFPC.Aa.wc();_IFPC.clear()}}
function ig_Za(a){var b=_IFPC.fb(a)[0],c=ig_;try{c=window.parent.frames[b]}catch(d){}try{if(!c&&window.parent.parent.frames[b]!=window.parent){window.parent.parent.frames[b].setTimeout(function(){},0);c=window.parent.parent.frames[b]}}catch(e){}if(!c)c=window.parent.parent;if(!c||c._IFPC==undefined)c=ig_;else{b=function(){c._IFPC.handleRequest(a)};window.ActiveXObject?b():c.setTimeout(b,0)}}
function ig__a(a){a=_IFPC.fb(a);var b=a.shift(),c=a.shift(),d=a.shift(),e=a.shift(),f=a.shift();a=a.shift();b=b+"_"+c;_IFPC.M[b]||(_IFPC.M[b]=[]);_IFPC.M[b].push([e,f]);if(_IFPC.M[b].length==d){_IFPC.M[b].sort(function(g,l){return parseInt(g[0],10)-parseInt(l[0],10)});f="";for(e=0;e<d;e++)f+=_IFPC.M[b][e][1];_IFPC.M[b]=ig_;e=_IFPC.fb(f);b=e.shift();c=e.shift();d=e.shift();f=e.shift();var h=_IFPC.Ve(c);if(h){a=h.apply(ig_,e);if(_IFPC.of(f)){a.unshift(f);_IFPC.call(b,_IFPC.Nb,a,d,ig_,"")}}else if(a)throw new Error("Service "+
c+" not registered.");}}function ig_0a(a){return _IFPC.ma.hasOwnProperty(a)?_IFPC.ma[a]:ig_}function ig_1a(a){var b="";if(a&&typeof a=="function"){b=_IFPC.Qe();_IFPC.P[b]=a}return b}function ig_2a(a){if(_IFPC.P.hasOwnProperty(a))_IFPC.P[a]=ig_}function ig_3a(a){if(a&&_IFPC.P.hasOwnProperty(a))return _IFPC.P[a];return ig_}function ig_4a(){return _IFPC.Mb+_IFPC.ge++}function ig_5a(a){return(a+"").indexOf(_IFPC.Mb)==0}
function ig_6a(a){a=a.split("&");for(var b=0;b<a.length;b++){var c=decodeURIComponent(a[b]);try{c=ig_G.parse(c)}catch(d){}a[b]=c}return a}function ig_7a(a){for(var b=[],c=0;c<a.length;c++){var d=ig_G.stringify(a[c]);b.push(encodeURIComponent(d))}return b.join("&")}function ig_8a(a){var b=_IFPC.Je(a);if(b){for(var c=[],d=1;d<arguments.length;d++)c[c.length]=arguments[d];b.apply(ig_,c);_IFPC.Vg(a)}else throw new Error("Invalid callbackId");}var _IFPC={};
function ig_9a(a){if((a=window._argsUrl&&window._argsUrl(a))&&a.exp_rpc_js==1)window.FLAG_use_rpc_js=ig_a;if(window.FLAG_use_rpc_js)_IFPC={registerService:function(b,c){window.gadgets.rpc.register(b,function(){var d=this.a.slice(0);d.unshift(this.f);c.apply(ig_,d)})},unregisterService:function(b){window.gadgets.rpc.unregister(b)},handleRequest:function(b){window.gadgets.rpc.receive(b)},call:function(b,c,d,e,f,h,g,l){h=window.gadgets.rpc;if(e==h.getRelayUrl(".."))b="..";d||(d=[]);l||(d=d.slice(1));
d.unshift(f);d.unshift(c);d.unshift(b);h.call.apply(h,d)}};else{_IFPC={registerService:ig_Ua,unregisterService:ig_Va,call:ig_Wa,clear:ig_Xa,wc:ig_Ya,vh:ig_Za,th:ig_Za,handleRequest:ig__a,Mb:"cbid",Nb:"ifpc_callback",Aa:new ig_Ta,M:{},ma:{},P:{},ge:0,$a:0,hb:ig_b,Ve:ig_0a,Xf:ig_1a,Vg:ig_2a,Je:ig_3a,Qe:ig_4a,of:ig_5a,fb:ig_6a,xc:ig_7a,he:ig_8a};_IFPC.registerService(_IFPC.Nb,_IFPC.he)}}ig_9a(document.location.href);function _IG_Prefs_PrefsData(){}_IG_Prefs_PrefsData.prototype.value=ig_;
function _IG_Prefs(a){a=a;if(typeof remote_modules!=="object"){a=(a=_args().mid)?a:0;_IG_Prefs._parseURL(a);_IG_Prefs.Ca[a]=ig_b}else{if(!a)throw new Error("Module ID is required as first argument to _IG_Prefs() for inlined modules");_IG_Prefs.Ca[a]=ig_a}_IG_Prefs.g[_IG_Prefs.I+a]||(_IG_Prefs.g[_IG_Prefs.I+a]={});this.g=_IG_Prefs.g[_IG_Prefs.I+a];this.b=a;this.qh=/(.*)(\<ph.*?\>\s*(\<ex\>(.*?)\<\/ex\>)?\s*%1\s*\<\/ph\>)(.*)/}ig_c=_IG_Prefs.prototype;
ig_c.da=function(a,b){if(b==undefined)b=ig_;a=this.g[a];if(a==undefined)return b;a=a.value;return a!=undefined?a:b};ig_c.nb=function(a,b){return this.da(_IG_Prefs.l+a,b)};ig_c.getString=function(a){var b="";a=this.nb(a,b);return a!=ig_?a+"":b};ig_c.Me=function(a){var b=0;a=parseInt(this.nb(a,b),10);return isNaN(a)?b:a};ig_c.getBool=function(a){a=this.getString(a);return a==="true"||!!parseInt(a,10)};ig_c.Ie=function(a){return _IG_Prefs.Pd(this.nb(a,""))};ig_c.mg=function(a,b){this.set(a,_IG_Prefs.Od(b))};
ig_c.Ke=function(){return this.getString(".country")};ig_c.Ne=function(){return this.getString(".lang")};ig_c.Oe=function(a){return this.da(_IG_Prefs.Tb+a,"")+""};ig_c.set=function(){var a=Math.floor(arguments.length/2);if(a!=0){for(var b=[],c=0;c<a;++c){var d=arguments[c*2],e=_IG_Prefs.l+d,f=arguments[c*2+1]+"";this.Yg(e,f)&&b.push(d,f)}if(b.length!=0)_IG_Prefs.Ca[this.b]?_IG_Prefs._setP(this.b,b):_IFPC_SetPref(b)}};
function ig_$a(a){var b="todos",c=_ig_gmid_(a);b=(new _IG_Prefs(Number(c))).getString(b);if(navigator.userAgent.indexOf("MSIE")!=-1&&b.length>1E3){c=Math.ceil(b.length/1E3);for(var d=0;d<c;d++){var e=b.substr(d*1E3,1E3);ig_ab(a,e,d,c)}}else ig_ab(a,b)}function ig_ab(a,b,c,d){var e=_ig_gmid_(a);b=[b];d&&b.push(c,d);_IFPC.call(a,"populate_todos_pref",b,window._ifpc_relay_url[e],ig_,"http://"+window.location.host+"/ig/images/rpc_relay.html",ig_a,ig_a)}
window._IG_CONTAINER&&_IFPC.registerService("get_todos_pref_for_migration",ig_$a);_IG_Prefs.prototype.Se=function(){var a=["__module_id__="+this.b];for(var b in this.g)a.push(encodeURIComponent(b)+"="+encodeURIComponent(this.g[b].value));return a.join("&")};_IG_Prefs.prototype.dump=function(){document.write("<pre>");for(var a in this.g)document.writeln(a+" = "+this.da(a,ig_));document.write("</pre>")};
_IG_Prefs.prototype.Yg=function(a,b){var c=this.g[a];if(c&&c.value===b)return ig_b;if(c)c.value=b;else{c=new _IG_Prefs_PrefsData;c.value=b;this.g[a]=c}return ig_a};_IG_Prefs.Ca={};_IG_Prefs.g={};_IG_Prefs.I="m_";_IG_Prefs.l="up_";_IG_Prefs.Nd="up_";_IG_Prefs.Tb="msg_";_IG_Prefs.Ra={};_IG_Prefs.Ra[_IG_Prefs.Nd]="value";_IG_Prefs.jh=function(a,b){if(a.indexOf)return a.indexOf(b);else{for(var c=0;c<a.length;++c)if(a[c]===b)return c;return-1}};
_IG_Prefs._parseURL=function(a){_IG_Prefs.Ca[a]=ig_b;for(var b={},c=ig_f(),d=0;d<c.length;++d){var e=c[d].indexOf("=");if(e>=0){var f=c[d].substring(0,e);f=f.replace(/\+/g," ");e=c[d].substring(e+1);e=e.replace(/\+/g," ");e=_unesc(e);var h=ig_b;for(var g in _IG_Prefs.Ra)if(f.indexOf(g)===0){h=ig_a;f=f.substring(g.length);f=_IG_Prefs.l+f;b[f]=b[f]?b[f]:new _IG_Prefs_PrefsData;if(g===_IG_Prefs.hh||g===_IG_Prefs.gh)e=e=="true";b[f][_IG_Prefs.Ra[g]]=e;break}if(!h)if(f.indexOf(_IG_Prefs.Tb)===0)_IG_Prefs.O(a,
f,e);else if(f===".lang"||f===".country")_IG_Prefs.O(a,_IG_Prefs.l+f,e)}}if(window.IDIModule){b=window.IDIModule.getPrefs();for(d in b)_IG_Prefs.O(a,d,b[d])}else for(f in b)_IG_Prefs.O(a,f,b[f].value)};_IG_Prefs.O=function(a,b,c){a=_IG_Prefs.I+a;if(typeof _IG_Prefs.g[a]!=="object")_IG_Prefs.g[a]={};if(typeof _IG_Prefs.g[a][b]!=="object"){_IG_Prefs.g[a][b]=new _IG_Prefs_PrefsData;b=_IG_Prefs.g[a][b];b.value=c}};
_IG_Prefs.wg=function(a,b,c){var d=_IG_Prefs.I+a;if(typeof _IG_Prefs.g[d]!=="object")_IG_Prefs.O(a,b,c);else if(typeof _IG_Prefs.g[d][b]!=="object")_IG_Prefs.g[d][b]=new _IG_Prefs_PrefsData;a=_IG_Prefs.g[d][b];a.value=c};_IG_Prefs._addAll=function(a,b){for(var c=0;c<b.length;++c)_IG_Prefs.O(a,b[c][0],b[c][1])};_IG_Prefs.Od=function(a){var b=a.length&&a.join;if(b){b=[];for(var c=0;c<a.length;++c)b.push(a[c].replace(/\|/g,"%7C"));return b.join("|")}else return a};
_IG_Prefs.Pd=function(a){a=a.length>0?a.split("|"):[];for(var b=0;b<a.length;++b)a[b]=a[b].replace(/%7C/g,"|");return a};
_IG_Prefs.aa=function(a,b){a=_IG_Prefs.I+a;a=_IG_Prefs.g[a];if(a==ig_)return b;b=b.split("#");var c=b[0].split("?"),d=c;if(b.length>1&&("&"+b[1]).indexOf("&"+_IG_Prefs.l)!==-1&&(c.length===1||("&"+c[1]).indexOf("&"+_IG_Prefs.l)===-1))d=b;var e=[];if(d.length>1&&d[1].length!==0)e=d[1].split("&");for(var f=0;f<e.length;++f)e[f].indexOf(_IG_Prefs.l)===0&&e.splice(f--,1);for(var h in a)h.indexOf(_IG_Prefs.l)!==0||h.indexOf(_IG_Prefs.l+".lang")===0||h.indexOf(_IG_Prefs.l+".country")===0||h.indexOf(_IG_Prefs.l+
"synd")===0||e.push(_esc(h)+"="+_esc(a[h].value));d[1]=e.join("&");b[0]=c.join("?");return b.join("#")};_IG_Prefs._setPrefs=function(a,b){for(var c=Math.floor(b.length/2),d=0;d<c;++d){var e=_IG_Prefs.l+b[d*2],f=b[d*2+1];_IG_Prefs.wg(a,e,f)}};_IG_Prefs._setP=function(a,b){if(_args().synd!=="open"){for(var c=Math.floor(b.length/2),d=[],e=0;e<c;++e){var f=_IG_Prefs.l+b[e*2],h=b[e*2+1];d.push(_IG_Prefs.I+a+"_"+f+"="+_esc(h))}d.length!==0&&_xsetp(d.join("&"))}};
_exportClass("google.gadgets","Prefs",_IG_Prefs,["getString",_IG_Prefs.prototype.getString,"getInt",_IG_Prefs.prototype.Me,"getBool",_IG_Prefs.prototype.getBool,"getArray",_IG_Prefs.prototype.Ie,"setArray",_IG_Prefs.prototype.mg,"getLang",_IG_Prefs.prototype.Ne,"getCountry",_IG_Prefs.prototype.Ke,"getMsg",_IG_Prefs.prototype.Oe,"getPreloadedString",_IG_Prefs.prototype.Se,"set",_IG_Prefs.prototype.set,"dump",_IG_Prefs.prototype.dump]);var _IG_FR_viewType={HEADLINE:0,HEADLINE_AND_LEAD_STORY:1,SLIDESHOW:2},_IG_FR_divType={ENTRY:0,PLUSBOX:1,HEADLINE:2,OUTER_CONTENT:3,INNER_CONTENT:4,STATUS:5,DISPLAY:6,ENTRIES:7,MSG:8,PREVIEW_SNIPPET:9,MEDIA_RSS_INNER:10,SLIDESHOW:12,SUMMARY_IMAGE:13,ARTICLE:14,SLIDESHOW_IMAGE_DIV:15,MEDIA_RSS_OUTER:16,SLIDESHOW_IMAGE_ERROR_DIV:17};
function _IG_FR_divIdFor(a,b,c,d){switch(b){case _IG_FR_divType.ENTRY:return"ftl_"+a+"_"+c;case _IG_FR_divType.PLUSBOX:return"ft_"+a+"_"+c;case _IG_FR_divType.HEADLINE:return"f_e_"+a+"_"+c+"_link";case _IG_FR_divType.PREVIEW_SNIPPET:return"f_e_"+a+"_previewsnippet";case _IG_FR_divType.OUTER_CONTENT:return"fb_"+a+"_"+c;case _IG_FR_divType.SUMMARY_IMAGE:return"f_e_"+a+"_"+c+"_summaryimage";case _IG_FR_divType.INNER_CONTENT:return"fb_"+a+"_"+d;case _IG_FR_divType.STATUS:return"feed_"+a+"_statusmsg";
case _IG_FR_divType.MSG:return"feed_"+a+"_msg";case _IG_FR_divType.DISPLAY:return"feed_"+a+"_display";case _IG_FR_divType.ENTRIES:return"feed_"+a+"_entries";case _IG_FR_divType.MEDIA_RSS_INNER:return"f_e_"+a+"_mediarssinner";case _IG_FR_divType.SLIDESHOW:return"feed_"+a+"_slideshow";case _IG_FR_divType.ARTICLE:return"ftl_"+a+"_"+c+"_article";case _IG_FR_divType.SLIDESHOW_IMAGE_DIV:return"f_s_"+a+"_"+c+"_slideshowimage";case _IG_FR_divType.MEDIA_RSS_OUTER:return"f_e_"+a+"_mediarssouter";case _IG_FR_divType.SLIDESHOW_IMAGE_ERROR_DIV:return"f_s_"+
a+"_"+c+"_slideshowimageerror"}return""}function _IG_FR_fetchFeed(a,b,c){a.is_fetching=ig_a;_IG_FetchFeedAsJSON(a.url,function(d){a.is_fetching=ig_b;if(d&&d.Entry){a.has_entries=ig_a;a.feedData=d;if(a.renderer)a.renderer.feedData=d;b(a)}},c,ig_a)}function _IG_FR_getFeed(a){return window["FEED"+a]||{}}
function _IG_FR_toggle(a,b,c,d,e){c=c||"";d=d||"";var f=_gel(_IG_FR_divIdFor(a,_IG_FR_divType.PLUSBOX,b)),h=_gel(_IG_FR_divIdFor(a,_IG_FR_divType.OUTER_CONTENT,b)),g=_gel(_IG_FR_divIdFor(a,_IG_FR_divType.ENTRY,b));if(h.style.display!="none")ig_bb(f,h,g,c,a,b,e);else{var l=_IG_FR_getFeed(a);if(!l.has_entries&&!l.is_fetching)_IG_FR_fetchFeed(l,_IG_Callback(ig_cb,a,b,c,d,e),l.num_items+15);else{for(var k=0;k<l.num_items;++k){var m=_gel(_IG_FR_divIdFor(a,_IG_FR_divType.ENTRY,k));m&&ig_bb(_gel(_IG_FR_divIdFor(a,
_IG_FR_divType.PLUSBOX,k)),_gel(_IG_FR_divIdFor(a,_IG_FR_divType.OUTER_CONTENT,k)),m,c,a,k,e)}b=b;f=f;c=h;l=g;d=d;k=e;if(k==2){a=_IG_FR_getFeed(a);b==0&&a&&a.viewType==_IG_FR_viewType.HEADLINE_AND_LEAD_STORY&&a.hidePreviewSnippetAndMedia();a&&a.maybePopulateSummaryHtml(b)}f.className=ig_H(f)?"fminbox_reverse_directionality":"fminbox";f.title=d;if(_old_html||_use_old_feed_styles)f.className="fbox fminbox";c.style.display="";if(!k||k==1){c.style.maxHeight=c.offsetWidth*1.5+"px";l.className=ig_H(f)?
"sftl_reverse_directionality":"sftl"}if((!e||e==1)&&h.style.maxHeight&&parseInt(h.style.maxHeight,10)<ig_db(g.offsetWidth,h))h.style.height=h.style.maxHeight}}}function ig_cb(a,b,c,d,e,f){if(f!=2){a=a.feedData;for(var h=0;h<a.Entry.length;h++)if(a.Entry[h].ID&&a.Entry[h].ID!="no_id"){var g=_gel(_IG_FR_divIdFor(b,_IG_FR_divType.INNER_CONTENT,c,a.Entry[h].ID));if(g)g.innerHTML=a.Entry[h].Summary}}_IG_FR_toggle(b,c,d,e,f)}
function ig_H(a){return a.className.match(/reverse_directionality$/)=="reverse_directionality"}
function ig_bb(a,b,c,d,e,f,h){if(f==0&&h==2)(e=_IG_FR_getFeed(e))&&e.viewType==_IG_FR_viewType.HEADLINE_AND_LEAD_STORY&&e.showPreviewSnippetAndMedia();a.className=ig_H(a)?"fmaxbox_reverse_directionality":"fmaxbox";a.title=d;if(_old_html||_use_old_feed_styles)a.className="fbox fmaxbox";b.style.display="none";if(!h||h==1)b.style.maxHeight="";if(!h||h==1)c.className=ig_H(a)?"uftl_reverse_directionality":"uftl"}
function ig_db(a,b){var c=document.createElement("div");c.style.left=-screen.width;c.style.top=-screen.height;c.style.width=a;c.innerHTML=b.innerHTML;document.body.appendChild(c);a=c.clientHeight;document.body.removeChild(c);return a}function _IG_RegisterContainerScrollHandler(a){if(navigator.userAgent.indexOf("Firefox")>=0)window.addEventListener("scroll",a,ig_b);else window.onscroll=a}function _IG_GetContainerVisibleHeight(){return document.documentElement.clientHeight}
function _IG_GetContainerTotalHeight(){return document.body.scrollHeight}function _IG_GetContainerScrollTop(){return document.documentElement.scrollTop}function _IG_FR_getBaseUrl(a){var b=_gel("hl");b=b?b.value:"en";return"/reader/ig/feed/"+_esc(_IG_FR_getFeed(a).url)+"?hl="+b}function _IG_FR_setSrc(a,b){if(window._max_strategies){b=_IG_FR_getBaseUrl(a)+(b?"&i="+b:"");window._max_strategies[a]._updateIframeSrc(b)}}
function _IG_FR_maxModule(a,b,c){_IG_FR_setSrc(a,b);window._IG_maximize_view(a,"feed",c)}function _IG_FR_init(a){window._max_strategies&&_IG_callPostLoad(function(){window._max_strategies[a]=new window._IG_inlinedTransitionStrategy(a,_IG_FR_getBaseUrl(a),ig_,_IG_isIE())});_IG_AddModuleEventHandler(a,"unmaximize",function(){_IG_FR_setSrc(a)})};function ig_I(a){var b;b=a;var c;if(window.ActiveXObject){c=new ActiveXObject("Microsoft.XMLDOM");c.async=ig_b;c.validateOnParse=ig_b;c.resolveExternals=ig_b;c.loadXML(b)}else{c=new DOMParser;c=c.parseFromString(b,"text/xml")}b=c;if((c=b.documentElement)&&c.nodeName=="parsererror"||navigator.userAgent.indexOf("Safari")>=0&&_gelstn("parsererror",b)[0])return a;return b}var ig_eb=(new Date).getTime();
function ig_fb(a){if(!a.Uf&&!a.headers&&window._pl_data&&_pl_data[a.url]&&!(!isNaN(a.refreshInterval)&&a.refreshInterval>=0&&(new Date).getTime()>ig_eb+a.refreshInterval*1E3))if(a.Za){var b=ig_I(_pl_data[a.url]);a.callback(b)}else a.callback(_pl_data[a.url]);else{b="/ig/jsonp?";if(_et!="")b+="et="+_et+"&";if(!isNaN(a.refreshInterval)&&a.refreshInterval>=0)b=_appendMaxAgeParameter(b,a.refreshInterval);if(a.encoding)b+="enc="+_esc(a.encoding)+"&";if(a.headers){for(var c=[],d=0;d<a.headers.length;d++)c.push(_esc(a.headers[d][0]+
":"+a.headers[d][1]));b+="hdrs="+_esc(c.join(","))+"&"}b+="url="+_esc(a.url);_sendx(b,function(e){var f=e,h=a.url;e=a.callback;var g=a.Za;if(!f||f==""||f.length<=27||f.charAt(27)!="{")e(g?ig_:"");else{f=eval("("+f.substring(27)+")");if(h in f){h=f[h].body;e(g?ig_I(h):h)}}},ig_b,a.Uf)}}function ig_gb(a){var b={};for(var c in a)b[c]=a[c];return b}function _IG_FetchContent(a,b,c){c=c!=ig_&&typeof c=="object"?ig_gb(c):{};c.url=a;c.callback=b;c.Za=ig_b;ig_fb(c)}
function _IG_FetchXmlContent(a,b,c){c=c!=ig_&&typeof c=="object"?ig_gb(c):{};c.url=a;c.callback=b;c.Za=ig_a;ig_fb(c)}function ig_hb(a,b,c){_IG_FetchContent(a,function(d){if(d){d=ig_I(d);if(typeof d=="object"&&d.firstChild){var e=d.firstChild;e.nodeType==7&&e.nodeName=="xml"&&d.removeChild(e);b(d);return}}b(ig_)},c)}function ig_ib(a,b){var c="/ig/feedjson";_sendx(c,function(d){var e={};try{e=eval("("+d.slice(27)+")")}catch(f){e={}}for(var h in b){d=e[h]?e[h]:ig_;b[h](d)}b=ig_},ig_b,a)}
var ig_jb=ig_b,ig_kb=0,ig_J="",ig_K={};function _IG_FetchFeedAsJSON(a,b,c,d,e){if(typeof e!="object")e={};var f="fr_"+ig_kb++;a="url="+_esc(a);if(!isNaN(e.refreshInterval)&&e.refreshInterval>=0)a=_appendMaxAgeParameter(a,e.refreshInterval);if(c)a+="&val="+_esc(c);if(d)a+="&sum=1";c=f+"="+_esc(a);if(ig_jb){d={};d[f]=b;ig_ib(c,d)}else{if(ig_J!="")ig_J+="&";ig_J+=c;ig_K[f]=b}}function ig_lb(){ig_jb=ig_a;ig_J!=""&&ig_ib(ig_J,ig_K);ig_J="";ig_K=ig_}_IG_AddEventHandler("domload",ig_lb);
_exportSymbols("google.gadgets.Fetchers",["getContent",_IG_FetchContent,"getXMLContent",ig_hb,"getFeedAsJSON",_IG_FetchFeedAsJSON]);function ig_mb(a,b,c){var d=ig_t("m",b);if(d)d.ti=a;var e=_gel("m_"+b+"_title");if(e)e.innerHTML=_hesc(a);if(e=_gel("left_nav_m_"+b+"_title"))if(e=e.firstChild){e.title=a;e.innerHTML=_hesc(a);c||(e.offsetWidth==0?_IG_RegisterOnloadHandler(function(){ig_L(e)}):ig_L(e))}}
function ig_L(a,b){b=b||121;var c=a.title;if(!(a.offsetWidth<=b)){var d=0,e=c.length,f,h=c.match(/\(\d+\)$/);if(h=h?h[0]:""){h=" "+h;e=c.length-h.length;f=5*h.length;if(f>b>>1)h=""}for(;f=e-d>>1;){f=d+f;a.innerHTML=ig_nb(c,f,h);if(a.offsetWidth>b)e=f;else d=f}a.innerHTML=ig_nb(c,d,h)}}function ig_nb(a,b,c){a=[a.substring(0,b),"..."];c&&a.push(c);return _hesc(a.join(""))}function ig_M(a){return typeof a=="undefined"||!a||a=="undefined"}function ig_ob(a,b){ig_M(a)||ig_mb(b,_ig_gmid_(a))}
_IFPC.registerService("set_title",ig_ob);function _IG_SetTitle(a,b,c){ig_M(b)||ig_mb(a,b,c)}function _IG_SetTitleDir(a,b){if(!ig_M(b)){var c=ig_t("m",b);if(c)if(a)c.ti_dir=a;else delete c.ti_dir;if(c=_gel("m_"+b+"_title"))a?c.setAttribute("dir",a):c.removeAttribute("dir");if(c=_gel("left_nav_m_"+b+"_title"))a?c.setAttribute("dir",a):c.removeAttribute("dir")}}
function _IG_FormatLeftNavTitles(){_IG_RegisterOnloadHandler(function(){var a=_gel("full_nav"),b=_gelsbyregex("div",/^left_nav_m_\d+_title$/,a);if(b)for(a=0;a<b.length;++a){var c=b[a];(c=c.firstChild)&&ig_L(c)}for(a=0;a<_IG_MD.dt.length;++a)if(c=_gel("tab"+_IG_MD.dt[a].i+"_view_title")){b=c.className=="selected_tab_view_title"?80:100;(c=c.firstChild)&&ig_L(c,b)}})};function _delpromobox(){_xsetp("hp=0");var a=_gel("promobox");a.parentNode.removeChild(a);return ig_b}function _delmessage(){_xsetp("gm=0");var a=_gel("googlemessage");a.parentNode.removeChild(a);return ig_b}function _delpromomod(){_xsetp("pm=0");var a=_gel("promomod");a.parentNode.removeChild(a);return ig_b};var ig_N=new (function(){this.ka={};var a=window.onbeforeunload;window.onbeforeunload=function(){a&&a();ig_N.Af()}});ig_N.Wd=function(a,b){this.ka[a]=b};ig_N.dg=function(a){delete this.ka[a]};ig_N.da=function(a){return this.ka[a]};ig_N.Af=function(){var a=[];for(var b in this.ka)a.push(b+"="+this.ka[b]);if(a.length){b=ig_k();a="/ig/setp?et="+_et+"&"+a.join("&");b.open("GET",a,ig_b);b.send(ig_)}};function _IG_add_setp_parameter_onbeforeunload(a,b){ig_N.Wd(a,b)}
function _IG_remove_setp_parameter_onbeforeunload(a){ig_N.dg(a)}function _IG_get_setp_parameter_onbeforeunload(a){return ig_N.da(a)};var ig_O={Va:0,Ub:1,$b:2,Pb:3},ig_P=function(){function a(){var j=[],s=[];for(var i in k)if(k[i]&&!l[i])j.push(i);else!k[i]&&l[i]&&s.push(i);j.length?_IG_add_setp_parameter_onbeforeunload("exptabs",j.join(":")):_IG_remove_setp_parameter_onbeforeunload("exptabs");s.length?_IG_add_setp_parameter_onbeforeunload("coltabs",s.join(":")):_IG_remove_setp_parameter_onbeforeunload("coltabs");_IG_add_setp_parameter_onbeforeunload("roster",m+"")}function b(j){_gel("gadget_set"+j).style.display="block";_gel("triangle"+
j).className="v2minbox";k[j]=ig_a;_sendx("/ig/ui?xp=v2&action=expandTab&t="+j,ig_,ig_b,ig_)}function c(j){_gel("gadget_set"+j).style.display="none";_gel("triangle"+j).className="v2maxbox";k[j]=ig_b;_sendx("/ig/ui?xp=v2&action=collapseTab&t="+j,ig_,ig_b,ig_)}function d(){o.style.display="none";r.style.display="none";switch(e){case ig_O.Va:var j=_gel("section"+f+"_contents");j.className="section_contents leftunselectedtab leftborder";_gel("tab"+f).className="section_title unselected_section_title";
_gel("tab_separator"+f).style.display="";if(h)_gel("tab_separator"+h).style.display="";else if(_gel("tab_separator_bot"))_gel("tab_separator_bot").style.display="";break;case ig_O.Ub:j=_IG_getCurrentMaxId();j=_gel("left_nav_m_"+j+"_title");j.className="gadget_title";break;case ig_O.$b:j=_gel("updates_left_nav");j.className="gadget_title";break;case ig_O.Pb:j=_gel("shares_left_nav");j.className="gadget_title";break}}var e=ig_O.Va,f=ig_,h=ig_,g={},l={},k={},m=ig_a,o=ig_,r=ig_;return{nf:function(){o=
_gel("left_nav_top_rounded_corners");r=_gel("left_nav_bottom_rounded_corners")},sg:function(j){f=j},xh:function(j){e=j},Ue:function(){return f},qg:function(){for(var j=_gel("section"+f+"_contents").nextSibling;j;){if(j.id&&j.id.match(/section\d+_contents/)){h=j.id.match(/\d+/);break}j=j.nextSibling}},zh:function(){d()},Ic:function(j){d();j=_gel("left_nav_m_"+j+"_title");j.className="selected_gadget_title gadget_title leftselectedtab surroundborder";o.style.display="";r.style.display="";j.parentNode.insertBefore(o,
j);j.parentNode.insertBefore(r,j.nextSibling);e=ig_O.Ub},Jc:function(){d();var j=_gel("section"+f+"_contents");j.className="selected_section_contents leftselectedtab surroundborder";_gel("tab"+f).className="section_title selected_section_title";_gel("tab_separator"+f).style.display="none";if(h)_gel("tab_separator"+h).style.display="none";else if(_gel("tab_separator_bot"))_gel("tab_separator_bot").style.display="none";o.style.display="";r.style.display="";j.parentNode.insertBefore(o,j);j.parentNode.insertBefore(r,
j.nextSibling);e=ig_O.Va},kf:function(){d();var j=_gel("shares_left_nav");j.className="selected_gadget_title gadget_title leftselectedtab surroundborder";o.style.display="";r.style.display="";j.parentNode.insertBefore(o,j);j.parentNode.insertBefore(r,j.nextSibling);e=ig_O.Pb},lf:function(){d();var j=_gel("updates_left_nav");j.className="selected_gadget_title gadget_title leftselectedtab surroundborder";o.style.display="";r.style.display="";j.parentNode.insertBefore(o,j);j.parentNode.insertBefore(r,
j.nextSibling);e=ig_O.$b},Ng:function(j){var s=_gel("m_"+j+"_home_menu");if(s)s.style.display="none";if(j=_gel("m_"+j+"_canvas_menu"))j.style.display=""},Og:function(j){var s=_gel("m_"+j+"_canvas_menu");if(s)s.style.display="none";if(j=_gel("m_"+j+"_home_menu"))j.style.display=""},ff:function(j){if(j=_gel("left_nav_"+j+"_title"))j.style.display="none"},Bg:function(j){if(j=_gel("left_nav_"+j+"_title"))j.style.display=""},Vc:function(j){var s=_gel("m_"+j+"_b");g[j]=s&&s.style.display=="none";j=!_gel("remote_iframe_"+
j);var i=ig_a;s.style.display=j&&i?"none":""},Wc:function(j){var s=_gel("m_"+j+"_b");s.style.display=g[j]?"none":""},Eg:function(){if(f!="0"){_gel("rcbg").style.display="";_gel("col2").className="botborder"}},pd:function(){if(f=="0"){_gel("rcbg").style.display="";_gel("col2").className="botborder"}},Hc:function(){if(f=="0"){_gel("rcbg").style.display="none";_gel("col2").className="topbotborder"}},ze:function(j){l[j]=ig_a;k[j]=ig_a},le:function(j){l[j]=ig_b;k[j]=ig_b},Qg:function(j,s){if(!j)j=window.event;
j.cancelBubble=ig_a;j.stopPropagation&&j.stopPropagation();_gel("gadget_set"+s).style.display=="none"?b(s):c(s);a()},Pg:function(){if(_gel("talk_container")){m=!m;_gel("roster_triangle").className=m?"v2minbox":"v2maxbox";if(window.gTalkNotifier&&window.gTalkNotifier._setRosterExpanded)window.gTalkNotifier._setRosterExpanded(m);else _gel("talk_container").style.display=m?"":"none";_log("roster_toggle:"+(m?"1":"0"));a()}},kg:function(j){m=j},tf:function(){return m},hf:function(j){if(j=_gel(j))j.style.display=
"none"},sd:function(j){var s=_gel("DD_"+j+"_zip");if(s){j=(j=_gel("m_"+j+"_b"))&&j.style.display=="none";s.innerHTML=j?IG_MSGS.MAXG:IG_MSGS.MING}},rd:function(j){var s=_gel("m_"+j+"_b");j=s&&s.style.display=="none";if((s=s.nextSibling)&&s.className)s.className=j?"rnd_modtitle":"rnd_modboxin"}}}();
function _IG_LN_init(a){_IG_AddEventHandler("modulemaximize",ig_P.Ic);_IG_AddEventHandler("modulemaximize",ig_P.Ng);_IG_AddEventHandler("modulemaximize",ig_P.Vc);_IG_AddEventHandler("modulemaximize",ig_P.pd);_IG_AddEventHandler("moduleunmaximize",ig_P.Jc);_IG_AddEventHandler("moduleunmaximize",ig_P.Og);_IG_AddEventHandler("moduleunmaximize",ig_P.Wc);_IG_AddEventHandler("moduleunmaximize",ig_P.Hc);_IG_AddEventHandler("moduledelete",ig_P.ff);_IG_AddEventHandler("moduleundelete",ig_P.Bg);_IG_AddEventHandler("modulezip",
ig_P.sd);_IG_AddEventHandler("modulezip",ig_P.rd);_IG_AddEventHandler("moduleunzip",ig_P.sd);_IG_AddEventHandler("moduleunzip",ig_P.rd);_IG_RegisterOnloadHandler(ig_P.qg);_IG_RegisterOnloadHandler(ig_P.Eg);_IG_RegisterOnloadHandler(ig_P.nf);ig_P.sg(a)}
var _IG_get_selected_tab_id=ig_P.Ue,_IG_expand_tab_onload=ig_P.ze,_IG_collapse_tab_onload=ig_P.le,_IG_toggle_tab=ig_P.Qg,_IG_toggle_roster=ig_P.Pg,_IG_roster_state_onload=ig_P.kg,_IG_is_roster_expanded=ig_P.tf,_IG_hide_promo=ig_P.hf,_IG_maybe_unzip_module=ig_P.Vc,_IG_maybe_zip_module=ig_P.Wc,_IG_hideRoundedCornerOnRestore=ig_P.Hc,_IG_showRoundedCornerOnMaximize=ig_P.pd,_IG_highlight_invites=ig_P.kf,_IG_highlight_updates=ig_P.lf,_IG_highlight_module=ig_P.Ic,_IG_highlight_tab=ig_P.Jc;
